[package]
name = "auto-wordle"
version = "0.1.0"
edition = "2021"
authors = ["WunschUnreif"]
readme = "README.md"
description = "Solve wordle puzzles."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
